name: Docker Build and Push

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types:
      - closed
  release:
    types: [published]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push (latest)
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: soubai/kubestatu-operand:develop
      -
        name: Build and Push (latest)
        if: github.event.pull_request.merged == true
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: soubai/kubestatus-operand:develop
      -
        name: Build and Push New Release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: soubai/kubestatus-operand:${{ github.event.release.tag_name }}